---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: noiselab
description: Pro audio image optimized for low-spec devices

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true
    install: true

  - type: kargs
    arch: x86_64, aarch64
    kargs:
      - nosmt
      - preempt=full
      - nohz_full=all
      - threadirqs
      - nowatchdog
      - pcie_aspm=off
      - nosoftlockup
      - idle=poll
      - processor.max_cstate=1
      - systemd.unified_cgroup_hierarchy=0
      - usbcore.autosuspend=-1

  - type: dnf
    repos:
      cleanup: true
    install:
      allow-erasing: true
      packages:
        - alsa-firmware
        - alsa-tools
        - alsa-utils
        - alsamixergui
        - jack-mixer
        - pavucontrol
        - qjackctl
        - kernel-tools
        - realtime-setup
        - pipewire-alsa
        - pipewire-jack-audio-connection-kit
        - pipewire-pulseaudio
        - pipewire-utils
        - wireplumber
        - tuned-gtk
        - tuned-profiles-cpu-partitioning
        - tuned-profiles-realtime
        - htop
        - multimedia-menus
        - ardour9
        - mixxx
        - yoshimi
        - zita-at1
        - zita-rev1
        - fluidsynth
        - fluid-soundfont-gm
        - ffmpeg
        - cdrecord
        - mkisofs
        - cdda2wav
        - rar
        - gnome-menus

  - type: dnf
    repos:
      copr:
        - ycollet/audinux
    install:
      skip-unavailable: true
      allow-erasing: true
      packages:
        - Carla-mao
        - raysession
        - millisecond
        - jack-link
        - jack_capture
        - jack_delay
        - jack_utils
        - jackctlmmc
        - jackass
        - midiwake
        - timemachine
        - yabridge
        - yabridge-tui
        - wineasio
        - zrythm
        - lmms-mao-weekly
        - BespokeSynth
        - tenacity
        - mamba
        - samplehive
        - loopino
        - lsp-plugins
        - dpf-plugins
        - DISTRHO-Ports
        - cardinal
        - surge-xt
        - amsynth
        - guitarix
        - hamburger
        - valentine
        - dragonfly-reverb
        - puredata
        - plugdata
        - orca-lang

  - type: systemd
    system:
      enabled:
        - realtime-entsk.service
        - realtime-setup.service

  - type: gnome-extensions
    install:
      - TuneD Profile Switcher
      - Pipewire Settings
      - Apps Menu
      - PaperWM

  - type: signing
