#!/usr/bin/bash

set -eoux pipefail

if [[ "${1:-enable}" == 'enable' ]]; then
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://repo.librewolf.net/librewolf.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
  sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/negativo17-fedora-multimedia.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://negativo17.org/repos/fedora-nvidia.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://negativo17.org/repos/fedora-rar.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://negativo17.org/repos/fedora-cdrtools.repo

else
  for repo in \
    tailscale \
    librewolf \
    virtio-win \
    fedora-multimedia \
    fedora-nvidia \
    fedora-rar \
    fedora-cdrtools; \
  do
    sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/$repo.repo
  done
fi
