#!/usr/bin/sh

set -eoux pipefail

pkgs=(
  qemu-kvm
  qemu-img
  libvirt
  virt-install
  virt-manager
  virt-viewer
  virt-top
  virsh
  edk2-ovmf
  swtpm
  virtio-win
  libguestfs-tools
  python3-libguestfs
  virtualbox-guest-additions
)

dnf5 -y install "${pkgs[@]}"

# enable modular libvirt daemon and allow libvirt group to read VM images
# https://sysguides.com/install-kvm-on-linux
for drv in qemu interface network nodedev nwfilter secret storage; do
  systemctl enable virt${drv}d.service
  systemctl enable virt${drv}d{,-ro,-admin}.socket
done
setfacl -R -b /var/lib/libvirt/images
setfacl -R -m g:libvirt:rwX /var/lib/libvirt/images
setfacl -m d:g:libvirt:rwx /var/lib/libvirt/images
