#!/usr/bin/sh

set -oeux pipefail

dnf5 -y install \
  realtime-setup \
  tuned \
  tuned-profiles-realtime \
  tuned-profiles-nfv \
  tuned-profiles-nfv-host \

# configure realtime-setup
systemctl enable realtime-entsk.service
systemctl enable realtime-setup.service
sed -i '$s/unlimited/4194304/' /etc/security/limits.d/realtime.conf # change memlock value

# configure tuned
systemctl enable tuned.service
#tuned-adm profile realtime-virtual-host
# TODO: auto-set above profile, perhaps make a first-time setup script?
# TODO: add ujust script to help user set values in /etc/tuned/realtime-variables.conf and/or /etc/tuned/realtime-virtual-host-variables.conf
