#!/usr/bin/sh

set -eoux pipefail

pkgs=(
  yabridge
  wine.x86_64
  wine.i686
  wine-mono-bin
  mingw32-wine-gecko
  mingw64-wine-gecko
  wine-dxvk
  winetricks
  libcurl-gnutls
  pipewire-wineasio
)

dnf5 -y copr enable "patrickl/wine-tkg"
dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:patrickl:wine-tkg" "${pkgs[@]}"
dnf5 -y copr disable "patrickl/wine-tkg"
