#!/usr/bin/bash

set -eoux pipefail

pkgs=(
  jack-audio-connection-kit
  jack-audio-connection-kit-dbus
  pipewire-jack-audio-connection-kit
  ecryptfs-utils
  gocryptfs
  sirikali
  sox
  yq
  jq
)

dnf5 -y install "${pkgs[@]}"

# install negativo17 system/cli packages
dnf5 -y swap --from-repo="fedora-multimedia" ffmpeg ffmpeg
dnf5 -y swap --from-repo="fedora-multimedia" ffmpeg-libs ffmpeg-libs
dnf5 -y versionlock add ffmpeg ffmpeg-libs
dnf5 -y install --from-repo="fedora-rar" rar
dnf5 -y install --from-repo="fedora-cdrtools" \
  cdrecord \
  mkisofs \
  cdda2wav \
  schily-libs
dnf5 -y versionlock add cdrecord mkisofs cdda2wav schily-libs

# adjust miscellaneous services
systemctl --global enable podman.socket
systemctl --global enable systemd-tmpfiles-setup.service

# install from COPRs
dnf5 -y copr enable "ycollet/audinux"
dnf5 -y swap --from-repo="copr:copr.fedorainfracloud.org:ycollet:audinux" bluez bluez-mao
dnf5 -y copr disable "ycollet/audinux"
dnf5 versionlock add bluez-mao

dnf5 -y copr enable "bazzite-org/bazzite"
dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:bazzite-org:bazzite" xwiimote-ng
dnf5 -y copr disable "bazzite-org/bazzite"
