#!/usr/bin/bash

set -eoux pipefail

pkgs=(
  jack-audio-connection-kit
  jack-audio-connection-kit-dbus
  pipewire-jack-audio-connection-kit
  ecryptfs-utils
  gocryptfs
  sirikali
  libsecret
  sox
  yq
  jq
  zsh
  yt-dlp
  yt-dlp-bash-completion
  yt-dlp-zsh-completion
  input-remapper
  v4l2loopback
  ufw
  fastfetch
  vim
  nano
)

terra_pkgs=(
  8bitdo-udev-rules
  copyparty
  inputplumber
  joycond
  lan-mouse
  librepods
  nemu
  opentabletdriver
  pbpctrl
  scrcpy
  scrcpy-server
  scrcpy-bash-completion
  scrcpy-zsh-completion
  android-udev-rules
  scx-scheds
  scx-tools
  sndio
  starship
  topgrade
  vgmstream
  vo-aacenc
  voicevox
  x265
  xavs
  xavs2
  xavs2-libs
  xdvdfs
  zellij
  zola
  zola-bash-completion
  zola-zsh-completion
  zsh-autocomplete
)

dnf5 -y install "${pkgs[@]}"

dnf5 -y install --from-repo="terra,terra-extras,terra-mesa" "${terra_pkgs[@]}"

# install negativo17 system/cli packages
dnf5 -y remove --no-autoremove ffmpeg ffmpeg-libs
dnf5 -y install --from-repo="fedora-multimedia" ffmpeg ffmpeg-libs
dnf5 -y versionlock add ffmpeg ffmpeg-libs
dnf5 -y install --from-repo="fedora-rar" rar
dnf5 -y install --from-repo="fedora-cdrtools" \
  cdrecord \
  mkisofs \
  cdda2wav \
  schily-libs
dnf5 -y versionlock add cdrecord mkisofs cdda2wav schily-libs

# install from COPRs
#dnf5 -y remove --no-autoremove bluez
#dnf5 -y copr enable "ycollet/audinux"
#dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:ycollet:audinux" bluez-mao
#dnf5 -y copr disable "ycollet/audinux"
#dnf5 versionlock add bluez-mao

dnf5 -y copr enable "bazzite-org/bazzite"
dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:bazzite-org:bazzite" xwiimote-ng
dnf5 -y copr disable "bazzite-org/bazzite"

# adjust services
systemctl --global enable podman.socket
systemctl --global enable systemd-tmpfiles-setup.service
systemctl --global enable scx_loader.service
