#!/usr/bin/sh

set -eoux pipefail

fedora_pkgs=(
  cage
  niri
  wlr-randr
  librewolf
  tailscale
  gdisk
  gnome-disk-utility
  gnome-keyring
  gnome-keyring-pam
  tuned-gtk
  ptyxis
  brasero
  krita
  gimp
  flowblade
  ardour8
  twitter-twemoji-fonts
  xdg-desktop-portal-gtk
  xdg-desktop-portal-gnome
  gnome-keyring
  nautilus
  file-roller
  file-roller-nautilus
  zathura
  zathura-bash-completion
  zathura-zsh-completion
  zathura-plugins
  mako
  cmus
  deadbeef
  deadbeef-plugins
  mixxx
  obs-studio
  obs-studio-libs
  obs-studio-plugin-vlc-video
  obs-studio-plugin-x264
  lxpolkit
  swayidle
  swaylock
  swayimg
  udiskie
  sddm
)

multimedia_pkgs=(
  vlc
  vlc-cli
  vlc-plugins-all
  mpv
  mpv-libs
  makemkv
  libdvdcss
  blender
  mjpegtools
)

terra_pkgs=(
  WoeUSB-ng
  SwayOSD
  cleartype-fonts
  codium
  codium-marketplace
  feishin
  geist-font
  ghostty
  ghostty-bash-completion
  ghostty-zsh-completion
  ghostty-shell-integration
  ghostty-nautilus
  ghostty-vim
  ghostty-terminfo
  helium-browser-bin
  lowfi
  mission-center
  mpvpaper
  ms-core-fonts
  netto
  nerd-fonts
  open-in-mpv
  openutau
  spleen-fonts
  subtitleedit.bin
  sway-audio-idle-inhibit
  swww
  swww-bash-completion
  swww-zsh-completion
  trackiton-waveform
  walker
  elephant
  elephant-calc
  elephant-clipboard
  elephant-desktopapplications
  elephant-files
  elephant-menus
  elephant-providerlist
  elephant-runner
  elephant-symbols
  elephant-websearch
  waybar-niri-taskbar
  wluma
  xwayland-satellite
)

dnf5 -y install --from-repo="fedora-multimedia" "${multimedia_pkgs[@]}"

dnf5 -y install "${fedora_pkgs[@]}"

dnf5 -y install --from-repo="terra,terra-extras,terra-mesa" "${terra_pkgs[@]}"

# Install from COPRs
dnf5 -y copr enable "ublue-os/packages"
dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:ublue-os:packages" bazaar
dnf5 -y copr disable "ublue-os/packages"

dnf5 -y copr enable "bazzite-org/webapp-manager"
dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:bazzite-org:webapp-manager" webapp-manager
dnf5 -y copr disable "bazzite-org/webapp-manager"

dnf5 -y copr enable "julicen/atkinson-hyperlegible-fonts"
dnf5 -y install --from-repo="copr:copr.fedorainfracloud.org:julicen:atkinson-hyperlegible-fonts" \
  atkinson-hyperlegible-next-fonts \
  atkinson-hyperlegible-mono-fonts
dnf5 -y copr disable "julicen/atkinson-hyperlegible-fonts"

# TODO: make configuration files
