#!/usr/bin/sh

set -eoux pipefail

pkgs=(
  cosmic-desktop
  cage
  wlr-randr
  librewolf
  tailscale
  gdisk
  gnome-disk-utility
  gnome-keyring
  gnome-keyring-pam
  tuned-gtk
  ptyxis
  brasero
  krita
  gimp
  flowblade
  ardour8
  twitter-twemoji-fonts
)

dnf5 -y install "${pkgs[@]}"

dnf5 -y remove \
  cosmic-store \
  cosmic-term

# Install negativo17 multimedia packages
# TODO: ujust script that auto-registers makemkv
# http://www.makemkv.com/forum2/viewtopic.php?f=5&t=1053
dnf5 -y install --from-repo="fedora-multimedia" \
  vlc \
  vlc-cli \
  vlc-plugins-all \
  mpv \
  mpv-libs \
  makemkv \
  libdvdcss \
  blender \
  mjpegtools

# Install from COPRs
dnf5 -y copr enable "ublue-os/packages" && dnf5 -y copr disable "ublue-os/packages"
dnf5 -y install --enablerepo="copr:copr.fedorainfracloud.org:ublue-os:packages" \
  bazaar \
  ublue-fastfetch

dnf5 -y copr enable "bazzite-org/webapp-manager" && dnf5 -y copr disable "bazzite-org/webapp-manager"
dnf5 -y install --enablerepo="copr:copr.fedorainfracloud.org:bazzite-org:webapp-manager" webapp-manager

dnf5 -y copr enable "julicen/atkinson-hyperlegible-fonts" && dnf5 -y copr disable "julicen/atkinson-hyperlegible-fonts"
dnf5 -y install --enablerepo="copr:copr.fedorainfracloud.org:julicen:atkinson-hyperlegible-fonts" \
  atkinson-hyperlegible-next-fonts \
  atkinson-hyperlegible-mono-fonts

dnf5 -y copr enable "che/nerd-fonts" && dnf5 -y copr disable "che/nerd-fonts"
dnf5 -y install --enablerepo="copr:copr.fedorainfracloud.org:che:nerd-fonts" nerd-fonts

# install Thorium browser (SSE3 non-beta build)
THORIUM_TAG="M130.0.6723.174"
dnf5 -y install <(curl -sL https://api.github.com/repos/Alex313031/thorium/releases/tags/${THORIUM_TAG} | \
  jq -r '.assets[] | select(.name? | match("thorium-browser_.*_SSE3.rpm")) | .browser_download_url' | \
  wget -qi -)
unset -v THORIUM_TAG
