#!/usr/bin/bash

set -eoux pipefail

pkgs=(
  jack-audio-connection-kit
  jack-audio-connection-kit-dbus
  pipewire-jack-audio-connection-kit
  sox
  ublue-brew
  uupd
  usbmuxd
  yq
  ecryptfs-utils
  gocryptfs
  sirikali
)

for pkg in "${pkgs[@]}"; do
  dnf5 -y install $pkg
done

# install audinux patched bluez
dnf5 -y swap --repo="copr:copr.fedorainfracloud.org:ycollet:audinux" bluez bluez-mao
dnf5 versionlock add bluez-mao

# install wiimote support from bazzite COPR
dnf5 -y copr enable bazzite-org/bazzite
dnf5 -y install xwiimote-ng
dnf5 -y copr disable bazzite-org/bazzite

# install negativo17 patched ffmpeg
dnf5 -y install --repo="fedora-multimedia" ffmpeg

# setup homebrew
systemctl enable brew-setup.service
systemctl disable brew-upgrade.timer
systemctl disable brew-update.timer

# adjust miscellaneous services
systemctl --global enable podman.socket
systemctl --global enable systemd-tmpfiles-setup.service
