#!/usr/bin/bash

set -eoux pipefail

# configure realtime-setup
systemctl enable realtime-entsk.service
systemctl enable realtime-setup.service
sed -i '$s/unlimited/4194304/' /etc/security/limits.d/realtime.conf # change memlock value
# TODO: user will need to be in realtime, audio, jackuser, and pipewire groups! (also libvirt, though not directly related here)
# preferrably find some way to automate this (perhaps during an ISO installation?), otherwise have usermod command be a simple ujust script:
# sudo usermod -aG realtime,audio,jackuser,pipewire,libvirt $USER

# configure tuned
systemctl enable tuned.service
tuned-adm profile realtime-virtual-host
# TODO: add ujust script to help user set values in /etc/tuned/realtime-variables.conf and/or /etc/tuned/realtime-virtual-host-variables.conf

# nondestructively rename pipewire-jack entries so native JACK can be used
# TODO: provide a ujust script that toggles between pipewire-jack and native JACK by doing this
pushd /etc/ld.so.conf.d
mv pipewire-jack-i386.conf pipewire-jack-i386.disabled
mv pipewire-jack-x86_64.conf pipewire-jack-x86_64.disabled
popd

# enable modular libvirt daemon and allow libvirt group to read VM images
# https://sysguides.com/install-kvm-on-linux
for drv in qemu interface network nodedev nwfilter secret storage; do
  systemctl enable virt${drv}d.service
  systemctl enable virt${drv}d{,-ro,-admin}.socket
done
setfacl -R -b /var/lib/libvirt/images
setfacl -R -m g:libvirt:rwX /var/lib/libvirt/images
setfacl -m d:g:libvirt:rwx /var/lib/libvirt/images

# setup uupd updater
dnf5 remove -y ublue-os-update-services
systemctl disable rpm-ostreed-automatic.timer
systemctl disable flatpak-system-update.timer
systemctl --global disable flatpak-user-update.timer
systemctl disable brew-update.timer
systemctl disable brew-upgrade.timer
systemctl enable uupd.timer

# setup homebrew
systemctl enable brew-setup.service
systemctl disable brew-upgrade.timer
systemctl disable brew-update.timer

# adjust miscellaneous services
systemctl --global enable podman.socket
systemctl --global enable systemd-tmpfiles-setup.service
