#!/usr/bin/bash

set -eoux pipefail

# install and configure realtime-setup
dnf5 -y install realtime-setup
systemctl enable realtime-entsk.service
systemctl enable realtime-setup.service

# configure tuned
systemctl enable tuned.service

# remove pipewire-jack so pipewire becomes a JACK client
rm /usr/etc/ld.so.conf.d/pipewire-jack-*.conf || true
rm /etc/ld.so.conf.d/pipewire-jack-*.conf || true
dnf5 -y remove pipewire-jack-audio-connection-kit
