#!/usr/bin/bash

set -eoux pipefail

# valid KERNEL_FLAVOR variables: generic, lqx, xan, bazzite
# valid NVIDIA_VERSION variables: none, open, lts

if [[ "$KERNEL_FLAVOR" != "generic" ]]; then
  dnf5 -y remove --no-autoremove "$(rpm -qa --queryformat='%{NAME} ' 'kernel-*')"
  # already did a successful build with the bazzite kernel so putting that code here in case it ever comes in handy
  if [[ "$KERNEL_FLAVOR" == "bazzite" ]]; then
    dnf5 -y install \
      /tmp/bazzite-kernel/kernel-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-core-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-modules-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-modules-core-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-modules-extra-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-devel-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-devel-matched-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-tools-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-tools-libs-[0-9]*.rpm \
      /tmp/bazzite-kernel/kernel-common-[0-9]*.rpm \
    if [[ "$NVIDIA_VERSION" == "open" ]]; then dnf5 -y install /tmp/bazzite-kernel/kernel-nvidia-[0-9]*.rpm;
    elif [[ "$NVIDIA_VERSION" == "lts" ]]; then dnf5 -y install /tmp/bazzite-kernel/kernel-nvidia-closed-lts-[0-9]*.rpm; fi;
  else
    dnf5 -y install kernel-$KERNEL_FLAVOR-mao kernel-$KERNEL_FLAVOR-mao-headers rt-tests
  fi
fi

dnf5 versionlock add "$(rpm -qa --queryformat='%{NAME} ' 'kernel-*')"

# install additional cachyos packages
dnf5 -y copr enable bieszczaders/kernel-cachyos-addons
dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons.priority=1
dnf5 -y install \
  scx-scheds \
  scx-tools
dnf5 -y copr disable bieszczaders/kernel-cachyos-addons
dnf5 -y config-manager unsetopt copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons.priority=1
dnf5 versionlock add scx-scheds scx-tools

# install mesa packages
dnf5 -y install mesa mesa.i686

# install nvidia drivers if applicable
if [[ "$KERNEL_FLAVOR" != "bazzite" ]]; then
  dnf5 -y install nvidia-driver	nvidia-settings	akmod-nvidia nvidia-driver-libs.i686
  if [[ "$NVIDIA_VERSION" == "open" && "$(modinfo -l nvidia)" == "NVIDIA" ]]; then
    sed -i -e 's/kernel$/kernel-open/g' /etc/nvidia/kernel.conf && akmods --rebuild
  elif [[ "$NVIDIA_VERSION" == "lts" && "$(modinfo -l nvidia)" == "Dual MIT/GPL" ]]; then
    sed -i -e 's/kernel-open$/kernel/g' /etc/nvidia/kernel.conf && akmods --rebuild
  fi
fi
if [[ "$NVIDIA_VERSION" == "open" || "$NVIDIA_VERSION" == "lts" ]]; then
  mkdir -p /usr/lib/bootc/kargs.d/ && echo 'kargs = ["nvidia-drm.modeset=1"]' > /usr/lib/bootc/kargs.d/03-nvidia-drm.toml
fi
