#!/usr/bin/bash

set -euox pipefail

dnf5 -y remove "$(rpm -qa --queryformat='%{NAME} ' 'kernel-*')"

dnf5 -y install \
  /tmp/rpms/kernel/kernel-[0-9]*.rpm \
  /tmp/rpms/kernel/kernel-core-*.rpm \
  /tmp/rpms/kernel/kernel-modules-*.rpm \
  /tmp/rpms/kernel/kernel-devel-*.rpm \
  /tmp/rpms/kernel/kernel-tools-*.rpm \
  /tmp/rpms/kernel/kernel-common-*.rpm

if [[ "NVIDIA" == "closed" ]]; then dnf5 -y install /tmp/rpms/kernel/kernel-nvidia-closed-*.rpm;
elif [[ -n "$NVIDIA" ]]; then dnf5 -y install /tmp/rpms/kernel/kernel-nvidia-[0-9]*.rpm; fi

dnf5 versionlock add "$(rpm -qa --queryformat='%{NAME} ' 'kernel-*')"

# install additional cachyos packages
dnf5 -y copr enable bieszczaders/kernel-cachyos-addons
dnf5 -y install \
  scx-scheds \
  scx-tools
dnf5 -y copr disable bieszczaders/kernel-cachyos-addons
