#!/usr/bin/bash

set -eoux pipefail

# valid KERNEL_FLAVOR variables: generic, lqx, xan

if [[ "$KERNEL_FLAVOR" != "generic" ]]; then
  dnf5 -y remove --no-autoremove "$(rpm -qa --queryformat='%{NAME} ' 'kernel-*')"
  dnf5 -y install kernel-$KERNEL_FLAVOR-mao rt-tests
  rm /usr/lib/bootc/kargs.d/01-threadirqs.toml
fi

# install additional cachyos packages
dnf5 -y copr enable bieszczaders/kernel-cachyos-addons
dnf5 -y install \
  scx-scheds \
  scx-tools
dnf5 -y copr disable bieszczaders/kernel-cachyos-addons
