#!/usr/bin/bash

set -eoux pipefail

coprs=(
  ublue-os/staging
  ublue-os/packages
  ycollet/audinux
  patrickl/wine-tkg
  bazzite-org/webapp-manager
  scottames/ghostty
  che/nerd-fonts
  julicen/atkinson-hyperlegible-fonts
)

if [[ "${1:-enable}" == 'enable' ]]; then
  for copr in "${coprs[@]}"; do
    dnf5 -y copr enable "${copr}" && \
    dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:"${copr////:}".priority=98
  done

  dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:patrickl:wine-tkg.priority=1
  dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:ycollet:audinux.priority=2
else
  for copr in "${coprs[@]}"; do
    dnf5 -y copr disable "${copr}"
  done
fi
