#!/usr/bin/bash

set -eoux pipefail

if [[ "${1:-enable}" == 'enable' ]]; then
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://repo.librewolf.net/librewolf.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://negativo17.org/repos/fedora-multimedia.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://negativo17.org/repos/fedora-nvidia.repo
  dnf5 -y config-manager setopt "*negativo17*".priority=2
  dnf5 -y config-manager setopt "*fedora*".exclude="mesa-* kernel-core-* kernel-modules-* kernel-uki-virt-*"
  dnf5 -y config-manager setopt "*staging*".exclude="scx-tools scx-scheds kf6-* mesa* mutter*"

else
  for repo in \
    tailscale \
    librewolf \
    virtio-win \
    negativo17-fedora-multimedia \
    negativo17-fedora-nvidia; \
  do
    sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/$repo.repo
  done
fi
