#!/usr/bin/bash

set -eoux pipefail

if [[ "${1:-enable}" == 'enable' ]]; then
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://repo.librewolf.net/librewolf.repo
  sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/negativo17-fedora-multimedia.repo
  dnf5 -y config-manager setopt "*negativo17*".priority=2
  dnf5 -y config-manager setopt "*rpmfusion*".exclude="mesa-*" && \
  dnf5 -y config-manager setopt "*fedora*".exclude="mesa-* kernel-core-* kernel-modules-* kernel-uki-virt-*" && \
  dnf5 -y config-manager setopt "*staging*".exclude="scx-tools scx-scheds kf6-* mesa* mutter*"

else
  for repo in \
    tailscale \
    librewolf \
    negativo17-fedora-multimedia \
    sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/$repo.repo
  done
fi
