#!/usr/bin/bash

set -eoux pipefail

coprs='ublue-os/staging'
coprs+='ublue-os/packages'
coprs+='bazzite-org/bazzite'
coprs+='bazzite-org/bazzite-multilib'
coprs+='ycollet/audinux'
coprs+='bazzite-org/webapp-manager'

if [[ "${1:-enable}" == 'enable' ]]; then
  for copr in $coprs; do
    dnf5 -y copr enable $copr;
    dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:${copr////:}.priority=98
  done

  dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:audinux.priority=1
else
  for copr in $coprs; do
    dnf5 -y copr disable $copr;
  done
fi
