#!/usr/bin/bash

set -eoux pipefail

coprs=(
  ublue-os/staging
  ublue-os/packages
  bazzite-org/bazzite
  bazzite-org/bazzite-multilib
  ycollet/audinux
  patrickl/wine-tkg
  bazzite-org/webapp-manager
  scottames/ghostty
  che/nerd-fonts
  julicen/atkinson-hyperlegible-fonts
)

if [[ "${1:-enable}" == 'enable' ]]; then
  # this package (needed by Carla) is in Fedora repos
  # yet dnf complains about it being unavailable.
  # try installing it now before COPRS are enabled
  dnf5 -y install python3-pyliblo

  for copr in "${coprs[@]}"; do
    dnf5 -y copr enable "${copr}" && \
    dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:"${copr////:}".priority=98
  done

  dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:patrickl:wine-tkg.priority=91
  dnf5 -y config-manager setopt copr:copr.fedorainfracloud.org:ycollet:audinux.priority=90
else
  for copr in "${coprs[@]}"; do
    dnf5 -y copr disable "${copr}"
  done
fi
