#!/usr/bin/bash

set -eoux pipefail

if [[ "${1:-enable}" == 'enable' ]]; then

  dnf install --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release(,-extras,-mesa}
  dnf5 -y config-manager setopt "*terra*".priority=3 "*terra*".exclude="scx-tools scx-scheds"
  dnf5 -y config-manager setopt "terra-mesa".enabled=true

  dnf5 -y config-manager addrepo --overwrite --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo

  sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/negativo17-fedora-multimedia.repo
  dnf5 -y config-manager addrepo --from-repofile=https://negativo17.org/repos/fedora-rar.repo
  dnf5 -y config-manager setopt "*negativo17*".priority=5 "*negativo17*".exclude="mesa-* *xone*"
  dnf5 -y config-manager setopt "*rpmfusion*".priority=5 "*rpmfusion*".exclude="mesa-*" && \
  dnf5 -y config-manager setopt "*fedora*".exclude="mesa-* kernel-core-* kernel-modules-* kernel-uki-virt-*" && \
  dnf5 -y config-manager setopt "*staging*".exclude="scx-tools scx-scheds kf6-* mesa* mutter*"

else
  for repo in \
    terra \
    terra-extras \
    terra-mesa \
    tailscale \
    negativo17-fedora-multimedia \
    fedora-rar; do
    sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/$repo.repo
  done
fi
